### ISSUE TITLE
Demo broken due to SSL issue

### ISSUE THREAD

**Issue by levic** [plouc/mozaik-website#15]
Chrome 71

Trying to load the demo app at http://mozaik.herokuapp.com/ gives the (self-explanatory) console error

`mozaik.min.js:12 Mixed Content: The page at 'https://mozaik.herokuapp.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://mozaik.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.`

(The net result is a blank page)

**Comment by levic** [comment]
Also Firefox 65, same error but a bit less helpful:

`SecurityError: The operation is insecure.`

**Comment by kevintatou** [comment]
I think this might be the same issue.  
But i get 
`mozaik.min.js:12 Mixed Content: The page at 'https://mozaik.herokuapp.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://mozaik.herokuapp.com/'. This request has been blocked; this endpoint must be available over WSS.
x @ mozaik.min.js:12
initWs @ mozaik.min.js:12
n @ mozaik.min.js:17
o.emit @ mozaik.min.js:5
trigger @ mozaik.min.js:17
(anonymous) @ mozaik.min.js:13
d.callback @ mozaik.min.js:18
(anonymous) @ mozaik.min.js:18
r.emit @ mozaik.min.js:1
n.onreadystatechange @ mozaik.min.js:18
XMLHttpRequest.send (async)
d.end @ mozaik.min.js:18
loadConfig @ mozaik.min.js:13
n @ mozaik.min.js:17
o.emit @ mozaik.min.js:5
trigger @ mozaik.min.js:17
(anonymous) @ mozaik.min.js:17
setTimeout (async)
n.nextTick @ mozaik.min.js:18
triggerAsync @ mozaik.min.js:17
M @ mozaik.min.js:17
253.mozaik-ext-github @ mozaik.min.js:18
o @ mozaik.min.js:1
t @ mozaik.min.js:1
(anonymous) @ mozaik.min.js:1
mozaik.min.js:12 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at x (https://mozaik.herokuapp.com/mozaik.min.js:12:30452)
    at n.initWs (https://mozaik.herokuapp.com/mozaik.min.js:12:31317)
    at o.n (https://mozaik.herokuapp.com/mozaik.min.js:17:24925)
    at o.emit (https://mozaik.herokuapp.com/mozaik.min.js:5:27204)
    at n.trigger (https://mozaik.herokuapp.com/mozaik.min.js:17:25214)
    at https://mozaik.herokuapp.com/mozaik.min.js:13:391
    at d.callback (https://mozaik.herokuapp.com/mozaik.min.js:18:9788)
    at d.<anonymous> (https://mozaik.herokuapp.com/mozaik.min.js:18:5960)
    at d.r.emit (https://mozaik.herokuapp.com/mozaik.min.js:1:1991)
    at XMLHttpRequest.n.onreadystatechange (https://mozaik.herokuapp.com/mozaik.min.js:18:10643)
x @ mozaik.min.js:12
initWs @ mozaik.min.js:12
n @ mozaik.min.js:17
o.emit @ mozaik.min.js:5
trigger @ mozaik.min.js:17
(anonymous) @ mozaik.min.js:13
d.callback @ mozaik.min.js:18
(anonymous) @ mozaik.min.js:18
r.emit @ mozaik.min.js:1
n.onreadystatechange @ mozaik.min.js:18
XMLHttpRequest.send (async)
d.end @ mozaik.min.js:18
loadConfig @ mozaik.min.js:13
n @ mozaik.min.js:17
o.emit @ mozaik.min.js:5
trigger @ mozaik.min.js:17
(anonymous) @ mozaik.min.js:17
setTimeout (async)
n.nextTick @ mozaik.min.js:18
triggerAsync @ mozaik.min.js:17
M @ mozaik.min.js:17
253.mozaik-ext-github @ mozaik.min.js:18
o @ mozaik.min.js:1
t @ mozaik.min.js:1
(anonymous) @ mozaik.min.js:1`

In the console when going to the HTTPS secure https://mozaik.herokuapp.com/.

If i go to http://mozaik.herokuapp.com/ then it works. 
However in HTTPS it does not allow unsecure web socket servers communicating with it. So you need to secure your web socket server if you want to use https for your demo app.
